services:
  music:
    build:
      context: .
      args:
        API_SERVER: https://api.music.cloudiance.space
    container_name: music
    ports:
      - "3051:3051"
    networks:
      - cloudiance

networks:
  cloudiance:
    external: true
